api = "0.6"

[buildpack]
id = "heroku/ruby"
version = "2.0.0"
name = "Ruby"

[[stacks]]
id = "heroku-20"

[metadata]
ruby_url = "https://heroku-buildpack-ruby.s3.amazonaws.com/heroku-20/ruby-2.7.4.tgz"
