version: 2.1
orbs:
  pack: buildpacks/pack@0.2.4
  ruby: circleci/ruby@1.1.2
  shellcheck: circleci/shellcheck@2.2.0

references:
  hatchet: &hatchet
    run:
      name: Run test suite
      command: PARALLEL_SPLIT_TEST_PROCESSES=25 IS_RUNNING_ON_CI=1 bundle exec parallel_split_test spec/hatchet
  pack_cnb: &pack_cnb
    run:
      name: Run test suite
      command: bundle exec rspec spec/cnb
  docker_commands: &docker_commands
    run:
      name: Run test suite
      command: PARALLEL_SPLIT_TEST_PROCESSES="4" IS_RUNNING_ON_CI=1 bundle exec parallel_split_test spec/docker
  unit: &unit
    run:
      name: Run test suite
      command: PARALLEL_SPLIT_TEST_PROCESSES="4" IS_RUNNING_ON_CI=1 bundle exec parallel_split_test spec/unit
  hatchet_setup: &hatchet_setup
    run:
      name: Hatchet setup
      command: |
        bundle exec hatchet ci:setup

jobs:
  shellcheck:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - shellcheck/install
      - run:
          name: Check build,compile,detect,release and bash_functions.sh with shellcheck
          command: |
            shellcheck -x bin/build bin/compile bin/detect bin/release bin/support/bash_functions.sh
  unit:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps
      - <<: *hatchet_setup
      - <<: *unit
  hatchet:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps
      - <<: *hatchet_setup
      - <<: *hatchet
  pack_cnb:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - pack/install-pack:
          version: 0.23.0
      - ruby/install-deps
      - <<: *hatchet_setup
      - <<: *pack_cnb
  docker_commands:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - pack/install-pack:
          version: 0.23.0
      - ruby/install-deps
      - <<: *hatchet_setup
      - <<: *docker_commands

workflows:
  version: 2
  build:
    jobs:
      - shellcheck
      - unit
      - hatchet
      - pack_cnb
      - docker_commands

